name: CI Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Format + Linter
        run: cargo fmt --all -- --check && cargo clippy --all-targets

      - name: Tests unitaires
        run: cargo test

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test-and-check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compilation release
        run: cargo build --release

      - name : Installer Typst
        run : cargo install --locked typst-cli

      
      - name: Compilation du manuel Typst
        run: typst compile doc/manual.typ doc/manual.pdf
