name: Check Test Coverage

on:
  pull_request:


jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: "Cache cargo"
      id: cache-cargo
      uses: "actions/cache@v4"
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        save-always: true
        key: cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
        restore-keys: cargo-

    - name: Installer Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run cargo tarpaulin
      id: coverage
      run: |
        set -e
        OUTPUT=$(cargo tarpaulin --ignore-tests)
        echo "$OUTPUT"
        COVERAGE=$(echo "$OUTPUT" | grep "Coverage Results" | grep -oE '[0-9]+\.[0-9]+')
        echo "Extracted coverage: $COVERAGE%"
        echo "coverage=$COVERAGE" >> "$GITHUB_OUTPUT"

    - name: Comment warning if coverage < 50%
      if: ${{ steps.coverage.outputs.coverage < 50 }}
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT="Not enough tests"
        echo -e "$COMMENT"
        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "Content-Type: application/json" \
             -X POST \
             -d "$(jq -nc --arg body "$COMMENT" '{body: $body}')" \
             "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
             