name: Check Test Coverage

on:
  pull_request:


jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Installer Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run cargo tarpaulin
      id: coverage
      run: |
        set -e
        OUTPUT=$(cargo tarpaulin --ignore-tests)
        echo "$OUTPUT"
        COVERAGE=$(echo "$OUTPUT" | grep "Coverage Results" | grep -oE '[0-9]+\.[0-9]+')
        echo "Extracted coverage: $COVERAGE%"
        echo "coverage=$COVERAGE" >> "$GITHUB_OUTPUT"

    - name: Comment warning if coverage < 50%
      if: ${{ steps.coverage.outputs.coverage < 50 }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Not enough tests