name: Check Test Coverage

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Installer Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run cargo tarpaulin
      id: coverage
      run: |
        set -e
        OUTPUT=$(cargo tarpaulin --ignore-tests)
        echo "$OUTPUT"
        COVERAGE=$(echo "$OUTPUT" | grep "Coverage Results" | grep -oE '[0-9]+\.[0-9]+')
        echo "Extracted coverage: $COVERAGE%"
        echo "coverage=$COVERAGE" >> "$GITHUB_OUTPUT"

    - name: Add 'not-enough-tests' label if coverage < 50%
      if: ${{ steps.coverage.outputs.coverage < 50 }}
      run: |
        gh pr edit ${{ github.event.pull_request.number }} --add-label "not-enough-tests"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
