
name: Functionnal testing before release

on:
  pull_request:
    branches:
      - 'release/*'

jobs:
  Audit-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            
      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Start Rust server in background
        run: |
            cargo run --features testing &
            SERVER_PID=$!
            echo "Server started with PID $SERVER_PID"

            # Run your tests
            python testing/testing.py
            python testing/test_pilot.py
            python testing/test_samuel.py

            # Kill the server after tests
            kill $SERVER_PID
            
      