
name: Functionnal testing before release

on:
  pull_request:
    branches:
      - 'release/*'

jobs:
  Audit-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
            
      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Start Rust server in background
        run: |
            cargo run --features testing &
            SERVER_PID=$!
            echo "Server started with PID $SERVER_PID"
            
            echo "Waiting for server to be ready..."
            while true; do
            if curl -s http://localhost:9345/ping | grep -q "pong"; then
                echo "Server is up!"
                break
            fi
            echo "Server not ready yet, retrying..."
            sleep 1
            done

            # Run your tests
            python testing/testing.py test-rich
            python testing/test_pilot.py test-rich1
            python testing/test_samuel.py test-rich2

            # Kill the server after tests
            kill $SERVER_PID
            
      