name: CI Rust

on:
  pull_request:
    branches:
      - 'release/*'

jobs:
  heavy-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Cache cargo"
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: cargotest-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: cargotest-

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build avec heavy-testing
        run: cargo build --features heavy-testing

      - name : Tester avec heavy-testing
        run : cargo test --features heavy-testing
      
      - name : Installer cargo audit
        run :  cargo install cargo-audit --locked
      
      - name : Run un cargo audit sur les dépendences toml
        run : cargo audit bin Cargo.toml