name : matrix-compiling


on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

permissions:
  pull-requests: write 
  contents: read

jobs:
    matrix-compiling :
        
        strategy:
            matrix:
                version : [  1.85.0 , 1.88.0]
                os : [macos-latest , ubuntu-latest , windows-latest]
        
        runs-on: ${{matrix.os}}
        
        if :  contains(github.ref, 'feature/')
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: "Cache cargo"
              id: cache-cargo
              uses: "actions/cache@v4"
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
                restore-keys: cargo-

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{matrix.version}} 
                override: true    
                components: clippy 

            - name: Compilation release
              run: cargo build --release