name: Enforce PR Branch Policy

on:
  pull_request:
    # Trigger on PRs targeting release/* branches
    branches:
      - 'release/*'


jobs:
  check-pr-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR source branch is not allowed
        run: |

          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"

          if [[ "$SOURCE_BRANCH" == "main" || "$SOURCE_BRANCH" == bug/* ]]; then
            echo "Source branch '$SOURCE_BRANCH' is allowed."
            exit 0
          else
            echo "Error: PRs to release/* must originate from 'main' or 'bug/*' branches."
            exit 1
          fi
