name: Enforce PR Branch Policy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'release/*'

permissions:
  pull-requests: write 
  contents: read

jobs:
  enforce-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        id: check_branch
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Checking source branch: $SOURCE_BRANCH"

          if [[ "$SOURCE_BRANCH" == "main" || "$SOURCE_BRANCH" == bug/* ]]; then
            echo "allowed=true" >> $GITHUB_OUTPUT
          else
            echo "allowed=false" >> $GITHUB_OUTPUT
          fi


      - name: Close PR if source not allowed
        if: steps.check_branch.outputs.allowed == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"

          echo "Attempting to close PR #$PR_NUMBER because it violates branch policy."

          gh pr comment "$PR_NUMBER" \
            --repo "$REPO" \
            --body "This PR was automatically closed: PRs targeting \`release/*\` must originate only from \`main\` or \`bug/*\` branches."

          gh pr close "$PR_NUMBER" --repo "$REPO"


