name: Checks good origin branch for release

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'release/*'


jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.head_ref }} != "main" && ${{ github.head_ref }} != "bug/*"]; then
            echo "Merge requests to main branch are only allowed from main or bug branch."
            exit 1
          fi
