name: Rust Quality Check

on:
  pull_request:
    types: [opened, synchronize]



jobs:
  check-format-clippy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Check
        run: cargo check

      - name: Format
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy
