name: Rust Quality Check

on:
  pull_request:
    types: [opened, synchronize]




jobs:
  check-format-clippy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable


      - name: Checkout
        uses: actions/checkout@v4

      - name: "Cache cargo"
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable
      
      

      - name: Rust Check
        run: cargo check

      - name: Format
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy
