name: Test the action

on:
  pull_request:
    branches:
      - release/*
    types: [closed]

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Aquire code
        uses: actions/checkout@v2
      - name: "Cache cargo"
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/*.rs') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Compilation release
        run: cargo build --release

      - name: Extract version from branch name
        run: |
          BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          VERSION="${BRANCH_NAME#release/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=v$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
           
      - name: Create deb package
        run: |
          mkdir -p debbuild/DEBIAN
          mkdir -p debbuild/usr/local/bin
          mkdir -p debbuild/usr/local/man

          cp target/release/simeis-server debbuild/usr/local/bin/
                  
                  cat <<EOF > debbuild/usr/local/man

          .\" Manpage for simeis but not really hihi.
          .\" Contact no one to correct errors or typos. We don't do any
          .TH man 1 "04 july 2025" "1.0" "simeis"
          .SH NAME
          Simeis is a nice game if you forget about le destructeur de marché.
          .SH SYNOPSIS
          In a galaxy far, far away, you could fight oppression but instead, you are mining.
          .SH DESCRIPTION
          Go mine.
          .SH OPTIONS
          The nuseradd does not take any options. However, you can supply username.
          .SH SEE ALSO
          Nowhere, you must mine.
          .SH BUGS
          No known bugs.
          .SH AUTHOR
          Timothée Cercueil but the bot is mine.
          EOF

                  cat <<EOF > debbuild/DEBIAN/control
          Package: simeis-server
          Version: ${VERSION}
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Samuelza
          Description: Serveur simeis compilé en Rust
          EOF
                    dpkg-deb --build debbuild
                    mv debbuild.deb target/release/simeis-server-${VERSION}.deb


      - name: Build and export Docker image
        run: |
          cp target/release/simeis-server .
          docker build -t simeis-server:${VERSION} .
          docker save simeis-server:${VERSION} -o target/release/simeis-server-docker-${VERSION}.tar

      - name: Release the new binaries
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ env.TAG }}"
          name: "Release ${{ env.VERSION }}"
          body: |
            PR #${{ github.event.pull_request.number }} merged by @${{ github.actor }}
            [Workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Commit message:
            ${{ env.GIT_MESSAGE }}
          files: |
            target/release/simeis-server.exe
            target/release/libsimeis_data.rlib
            target/release/simeis-server-${{ env.VERSION }}.deb
            target/release/simeis-server-docker-${{ env.VERSION }}.tar
            doc/manual.pdf
          clear_attachments: true
