name: Test the action

on:
  pull_request:
    branches:
      - release/*
    types: [closed]

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Aquire code
        uses: actions/checkout@v2

      - name: Extract version from branch name
        run: |
          BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
          VERSION="${BRANCH_NAME#release/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=v$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Put commit hash/name in env variables
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Release the new binaries
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ env.TAG }}"
          name: "Release ${{ env.VERSION }}"
          body: |
            PR #${{ github.event.pull_request.number }} merged by @${{ github.actor }}
            [Workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Commit message:
            ${{ env.GIT_MESSAGE }}
          files: |
            target/release/simeis-server.exe
            target/release/libsimeis_data.rlib
            doc/manual.pdf
          clear_attachments: true
